version: "3.8"

services:
  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    volumes:
      - /docker-volumes/etc/letsencrypt/live/safegymapp.xyz/fullchain.pem:/etc/letsencrypt/live/safegymapp.xyz/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/safegymapp.xyz/privkey.pem:/etc/letsencrypt/live/safegymapp.xyz/privkey.pem
    networks:
      - docker-network
  api:
    build:
      context: .
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
