version: "3.8"

services:
  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  api:
    build:
      context: .
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
